name: 'terraform-Azure'
on:
  push:
    branches:
    - master
  pull_request:
env: 
      ROOT_PATH: '${{github.workspace}}'
      ARM_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
jobs:
  terraform_plan:
    name: 'terraform plan'
    runs-on: ubuntu-latest
    environment: production
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run shell
      run: |
        echo "thie is test"
        echo $ARM_CLIENT_ID
        echo ${{secrets.AZURE_CLIENT_ID}}
      shell: bash

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: terraform init
      run: terraform init
      working-directory: ${{ env.ROOT_PATH }}
    - name: terraform Plan
      run: terraform plan 
      working-directory: ${{ env.ROOT_PATH }}
  apply:
     name: 'Apply'
     runs-on: ubuntu-latest
     needs: terraform_plan
     environment:
        name: azure
        # As prod-env required reviewers is `dineshba`,
        # it will wait for approval from dineshba
        

     steps:
    #... checkout, setup, init terraform steps like plan
     - name: Terraform Apply
       run: terraform apply -auto-approve
       working-directory: ${{ env.ROOT_PATH }}
